import java.util.Map;
import java.util.HashMap;
import java.util.function.*;

// File generated by FunctionsListGenerator.java from FunctionsList.template

public class FunctionsList {
    public Map<String, Double> constants=new HashMap<String, Double>();
    public Map<String, Function<Double, Double>> oneArgumentFunctions=new HashMap<String, Function<Double, Double>>();
    public Map<String, BiFunction<Double, Double, Double>> twoArgumentsFunctions=
           new HashMap<String, BiFunction<Double, Double, Double>>();
    FunctionsList(){
        constants.put("PI", Math.PI);
        constants.put("E", Math.E);
        oneArgumentFunctions.put("sin", Math::sin);
        oneArgumentFunctions.put("cos", Math::cos);
        oneArgumentFunctions.put("tan", Math::tan);
        oneArgumentFunctions.put("asin", Math::asin);
        oneArgumentFunctions.put("acos", Math::acos);
        oneArgumentFunctions.put("atan", Math::atan);
        oneArgumentFunctions.put("sinh", Math::sinh);
        oneArgumentFunctions.put("cosh", Math::cosh);
        oneArgumentFunctions.put("tanh", Math::tanh);
        oneArgumentFunctions.put("abs", Math::abs);
        twoArgumentsFunctions.put("pow", Math::pow);
        twoArgumentsFunctions.put("min", Math::min);
        twoArgumentsFunctions.put("max", Math::max);

        oneArgumentFunctions.put("ln", Math::log);
        twoArgumentsFunctions.put("log", (Double a, Double b)->Math.log(a)/Math.log(b));
    }
    public boolean isFunction(String name){
        return oneArgumentFunctions.containsKey(name) 
            || twoArgumentsFunctions.containsKey(name);
    }
    static FunctionsList instance;
    public static FunctionsList getInstance(){
        if(instance==null){
            instance=new FunctionsList();
        }
        return instance;
    }
}
