import java.util.Map;
import java.util.HashMap;
import java.util.function.*;

// File generated by FunctionsListGenerator.java

public class FunctionsList {
    public Map<String, Double> constants=new HashMap<String, Double>();
    public Map<String, Function<Double, Double>> oneArgumentFunctions=new HashMap<String, Function<Double, Double>>();
    public Map<String, BiFunction<Double, Double, Double>> twoArgumentsFunctions=
           new HashMap<String, BiFunction<Double, Double, Double>>();
    FunctionsList(){
constants.put("PI", Math.PI);
constants.put("E", Math.E);
oneArgumentFunctions.put("sin", Math::sin);
oneArgumentFunctions.put("cos", Math::cos);
oneArgumentFunctions.put("abs", Math::abs);
twoArgumentsFunctions.put("pow", Math::pow);
twoArgumentsFunctions.put("min", Math::min);
twoArgumentsFunctions.put("max", Math::max);
oneArgumentFunctions.put("ln", Math::log);
twoArgumentsFunctions.put("log", (Double a, Double b)->Math.log(a)/Math.log(b));
   }
   static FunctionsList instance;
   public static FunctionsList getInstance(){
       if(instance==null){
           instance=new FunctionsList();
       }
       return instance;
   }
}
